version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_HOST={DB_HOST}
      - DB_PORT={DB_PORT}
      - DB_USER={DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME={DB_NAME}
      - AZURE_STORAGE_ACCOUNT=${AZURE_STORAGE_ACCOUNT}
      - AZURE_STORAGE_KEY=${AZURE_STORAGE_KEY}
      - AZURE_STORAGE_CONTAINER=${AZURE_STORAGE_CONTAINER}
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrongPassword
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
